// Sahakar Gig Platform Mock Data - SIH26089 (Ministry of Cooperation)

export const SERVICE_CATEGORIES = [
  {
    id: 'electrical',
    name: 'Electricians & Wiring',
    icon: 'Zap',
    badge: 'High Demand',
    desc: 'Fault repairing, MCB installation, appliance wiring, LED fitting & earthing',
    basePrice: 299,
    workersAvailable: 42
  },
  {
    id: 'plumbing',
    name: 'Plumbing & Sanitation',
    icon: 'Droplets',
    badge: 'Popular',
    desc: 'Pipe leak fix, tap fitting, tank cleaning, toilet repairs & drainage clearing',
    basePrice: 249,
    workersAvailable: 38
  },
  {
    id: 'carpentry',
    name: 'Carpentry & Woodwork',
    icon: 'Hammer',
    badge: 'Certified',
    desc: 'Furniture repair, door lock installation, custom shelving & modular fitting',
    basePrice: 349,
    workersAvailable: 29
  },
  {
    id: 'painting',
    name: 'Painters & Wall Polish',
    icon: 'Paintbrush',
    badge: 'Eco-Friendly',
    desc: 'Interior/exterior whitewash, texture paint, waterproofing & wood polish',
    basePrice: 499,
    workersAvailable: 31
  },
  {
    id: 'caregiver',
    name: 'Caregivers & Elderly Care',
    icon: 'HeartHandshake',
    badge: 'Verified Skilled',
    desc: 'Daily mobility assistance, medication routine, post-op nursing & companionship',
    basePrice: 599,
    workersAvailable: 24
  },
  {
    id: 'domestic_help',
    name: 'Domestic Helpers & Cooks',
    icon: 'Utensils',
    badge: 'Background Checked',
    desc: 'Home cooking, dishwashing, deep house cleaning, laundry & child oversight',
    basePrice: 299,
    workersAvailable: 65
  },
  {
    id: 'driver',
    name: 'Drivers & Valet',
    icon: 'Car',
    badge: 'On-Demand',
    desc: 'Outstation trips, daily commute driver, commercial transport & night valet',
    basePrice: 399,
    workersAvailable: 19
  },
  {
    id: 'gardener',
    name: 'Gardeners & Landscaping',
    icon: 'Sprout',
    badge: 'Green Skill',
    desc: 'Lawn trimming, plant potting, organic pest control & balcony garden setup',
    basePrice: 279,
    workersAvailable: 16
  },
  {
    id: 'cleaning',
    name: 'Deep Cleaning & Sanitization',
    icon: 'Sparkles',
    badge: 'Govt Approved',
    desc: 'Sofa/carpet shampooing, kitchen deep clean, bathroom scrubbing & pest control',
    basePrice: 449,
    workersAvailable: 47
  },
  {
    id: 'technician',
    name: 'Appliance Technicians',
    icon: 'Wrench',
    badge: 'Expert Master',
    desc: 'AC service & gas refill, refrigerator, washing machine & RO water filter repair',
    basePrice: 399,
    workersAvailable: 33
  }
];

export const SAMPLE_WORKERS = [
  {
    id: 'WKR-101',
    name: 'Ramesh Kumar Verma',
    role: 'Master Electrician',
    categoryId: 'electrical',
    society: 'South Delhi Labour Cooperative Federation #402',
    societyRegNo: 'ND-LAB-2018-992',
    experience: '12 Years',
    rating: 4.9,
    reviewsCount: 142,
    completedJobs: 489,
    distanceKm: 1.2,
    badge: 'Govt Certified',
    hourlyRate: 350,
    photo: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&auto=format&fit=crop&q=80',
    verified: true,
    verificationDate: '2024-01-15',
    policeCleared: true,
    insuranceCovered: true,
    insurancePolicy: 'PM-Suraksha-Bima #8839201',
    phone: '+91 98765 43210',
    location: 'Lajpat Nagar IV, New Delhi',
    lat: 28.5672,
    lng: 77.2435,
    skills: ['3-Phase Wiring', 'Appliance Earthing', 'Industrial Panel Box', 'Smart Meter Fitting'],
    standbySOS: true
  },
  {
    id: 'WKR-102',
    name: 'Sunita Devi',
    role: 'Senior Caregiver & Nurse',
    categoryId: 'caregiver',
    society: 'Mahila Utthan Sahakari Samiti #108',
    societyRegNo: 'DL-WOM-2020-112',
    experience: '8 Years',
    rating: 4.95,
    reviewsCount: 210,
    completedJobs: 620,
    distanceKm: 1.8,
    badge: 'Coop Leader',
    hourlyRate: 400,
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    verified: true,
    verificationDate: '2023-11-20',
    policeCleared: true,
    insuranceCovered: true,
    insurancePolicy: 'Sahakar Health Shield #90214',
    phone: '+91 98123 55678',
    location: 'Defence Colony, New Delhi',
    lat: 28.5721,
    lng: 77.2312,
    skills: ['Geriatric Care', 'Physiotherapy Assist', 'Vital Monitoring', 'Dementia Care'],
    standbySOS: true
  },
  {
    id: 'WKR-103',
    name: 'Gurpreet Singh',
    role: 'Sanitation & Plumbing Expert',
    categoryId: 'plumbing',
    society: 'Capital Labour Construction & Maintenance Society',
    societyRegNo: 'DL-LAB-2016-044',
    experience: '10 Years',
    rating: 4.85,
    reviewsCount: 98,
    completedJobs: 340,
    distanceKm: 2.4,
    badge: 'Master Plumber',
    hourlyRate: 320,
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    verified: true,
    verificationDate: '2024-02-10',
    policeCleared: true,
    insuranceCovered: true,
    insurancePolicy: 'PM-Jeevan-Jyoti #776211',
    phone: '+91 99543 21098',
    location: 'Greater Kailash 1, New Delhi',
    lat: 28.5482,
    lng: 77.2341,
    skills: ['Hydro-Jetting Pipe Clearing', 'CPVC Fitting', 'Geyser Installation', 'Overhead Tank Clean'],
    standbySOS: false
  },
  {
    id: 'WKR-104',
    name: 'Mohd. Imran Khan',
    role: 'Master Carpenter & Joiner',
    categoryId: 'carpentry',
    society: 'National Craft Workers Cooperative Union',
    societyRegNo: 'IN-LAB-2015-883',
    experience: '15 Years',
    rating: 4.9,
    reviewsCount: 175,
    completedJobs: 512,
    distanceKm: 3.1,
    badge: 'Craft Specialist',
    hourlyRate: 380,
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    verified: true,
    verificationDate: '2023-09-01',
    policeCleared: true,
    insuranceCovered: true,
    insurancePolicy: 'Craft Workers Mutual Shield #1109',
    phone: '+91 97112 88901',
    location: 'Okhla Phase 3, New Delhi',
    lat: 28.5355,
    lng: 77.2611,
    skills: ['Modular Kitchen Fitting', 'Antique Restoration', 'Door Lock Installation', 'Plywood Work'],
    standbySOS: true
  },
  {
    id: 'WKR-105',
    name: 'Asha Rani',
    role: 'Culinary & Domestic Housekeeper',
    categoryId: 'domestic_help',
    society: 'Delhi Mahila Shramik Sahakari Bank Federation',
    societyRegNo: 'DL-SHR-2021-309',
    experience: '6 Years',
    rating: 4.88,
    reviewsCount: 130,
    completedJobs: 410,
    distanceKm: 0.9,
    badge: 'Top Rated',
    hourlyRate: 280,
    photo: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
    verified: true,
    verificationDate: '2024-03-02',
    policeCleared: true,
    insuranceCovered: true,
    insurancePolicy: 'Shramik Kalyan Bima #99401',
    phone: '+91 98987 11223',
    location: 'Kotla Mubarakpur, New Delhi',
    lat: 28.5790,
    lng: 77.2255,
    skills: ['North & South Indian Cuisine', 'Deep Kitchen Sanitization', 'Fabric Care', 'Meal Prep'],
    standbySOS: false
  }
];

export const INITIAL_BOOKINGS = [
  {
    id: 'BK-2026-8801',
    serviceName: 'Electrician & Wiring Repair',
    workerName: 'Ramesh Kumar Verma',
    workerRole: 'Master Electrician',
    society: 'South Delhi Labour Cooperative Federation #402',
    date: '2026-09-04',
    time: '10:00 AM',
    status: 'Confirmed',
    address: 'B-42, Gulmohar Park, New Delhi',
    totalAmount: 399,
    workerPayout: 359,
    societyDividend: 20,
    welfareContribution: 20,
    paymentStatus: 'Paid via UPI',
    otp: '4892'
  },
  {
    id: 'BK-2026-8794',
    serviceName: 'Elderly Caregiver Session (4 Hrs)',
    workerName: 'Sunita Devi',
    workerRole: 'Senior Caregiver',
    society: 'Mahila Utthan Sahakari Samiti #108',
    date: '2026-09-03',
    time: '02:00 PM',
    status: 'In Progress',
    address: 'Flat 102, Green Park Main, New Delhi',
    totalAmount: 1199,
    workerPayout: 1079,
    societyDividend: 60,
    welfareContribution: 60,
    paymentStatus: 'Paid via NetBanking',
    otp: '1093'
  }
];

export const PENDING_VERIFICATIONS = [
  {
    id: 'VER-901',
    name: 'Sanjay Vishwakarma',
    role: 'Technician & Refrigerator Expert',
    society: 'North District Labour Cooperative Federation',
    phone: '+91 98111 00299',
    appliedDate: '2026-09-02',
    aadharVerified: true,
    policeVerificationDoc: 'Police_Clearance_DL2026.pdf',
    skillCertificateDoc: 'ITI_Electrical_Certificate_2020.pdf',
    status: 'Pending Verification'
  },
  {
    id: 'VER-902',
    name: 'Pooja Sharma',
    role: 'Caregiver & Nursing Attendant',
    society: 'Mahila Swavalamban Sahakari Society #55',
    phone: '+91 99200 44112',
    appliedDate: '2026-09-03',
    aadharVerified: true,
    policeVerificationDoc: 'Police_Clearance_DL8821.pdf',
    skillCertificateDoc: 'Nursing_Attendant_Diploma.pdf',
    status: 'Pending Verification'
  }
];

export const FEDERATION_STATS = {
  totalRegisteredWorkers: 14850,
  activeSocieties: 142,
  completedJobsMonth: 42390,
  fairWagePaid: '₹1.84 Crore',
  welfareFundBalance: '₹28.5 Lakhs',
  activeInsurancePolicies: 13910,
  avgWorkerRating: 4.88,
  commercialCutComparison: '30% saved from private intermediaries'
};
